export const FETCH_PROCITEMS = 'FETCH_PROCITEMS'
export const RETRIEVED_PROCITEMS = 'RETRIEVED_PROCITEMS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const FILTER_SEARCH_RESULTS = 'FILTER_SEARCH_RESULTS'
export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT'

export const ADD_TO_FOLDER1 = 'ADD_TO_FOLDER1'
export const ADD_TO_FOLDER2 = 'ADD_TO_FOLDER2'
export const ADD_TO_FOLDER3 = 'ADD_TO_FOLDER3'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
